<html>
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="text-center">
<form class="form-reg">
    <h1>Registration</h1>
    <label class="reg-label">Enter your name:</label>
    <input type="text" class="login-input" id="nameInput" placeholder="name">
    <label class="reg-label">Enter your email:</label>
    <input type="email" class="login-input" id="emailInput" placeholder="email"></input>
    <label class="reg-label">Enter your password:</label>
    <input type="password" class="login-input" id="passwordInput" placeholder="password"></input>
    <button type="submit" class="submit-button">Registration</button>
</form>
<script type="text/javascript" src="js/angular.min.js"></script>
</body>
</html>